### ISSUE TITLE
[Bug] Rules don't match for Managed Users

### ISSUE THREAD

**Issue by scudre** [Maintainerr/Maintainerr#644] opened 2023-12-08 21:24 UTC
**Describe the bug**
The 'Users that watch the show...' rule criteria does not match for local managed users. 

**To Reproduce**
1. Create a new rule
2. Use the 'Users that watch the show...' rule criteria for a managed user
3. Verify shows watched by user are not populated in collection 
4. Modify rule to be a plex user
5. Verify that collection now is populated for the plex user.

**Expected behavior**
Watch history matching should work for both managed users and plex users

**Device (please complete the following information):**
 - OS: Ubuntu 20.04
 -  latest released docker image as of Dec 1 2023

**Additional context**
Tried this with managed user with an uppercase starting name.  Tried the create rule that matched case exactly.  Also attempted to make rule with all lowercase name.  No luck matching on the user's watch history.

Seems like this should work?  I reviewed the code for the plex api getter and saw it was pulling users from the /accounts api.  I queried this api on my server and verified it was returning back the managed users just fine.

**Comment by jorenn92** [comment] 2023-12-08 23:35
Good catch, i never tried managed users.  i’ll look into it.

**Comment by jorenn92** [comment] 2024-01-30 11:01
After testing on the development image, I found that it functions properly for managed users. Can you try again after the next release? It might already be fixed due to other changes.

Fyi, I did observe that Plex no longer generates play history records when an item is marked as watched, a behavior consistent across both managed and normal users. This is likely a bug on Plex's end, but something to take in consideration when testing.

Maintainerr currently has no way of knowing if something was watched if Plex doesn't save it in the item's play history. At least until i implement Tautulli integration.

**Comment by corotte** [comment] 2024-02-05 18:20
Tested it today and it seem to work fine since 2.0.0 release for managed user.
I was also able to use "Plex - [list] Viewed by (username)" and it worked but it was on a film related library.

**Comment by jorenn92** [comment] 2024-02-10 00:36
Closing this since it’s not reproducible anymore. Please create a new issue if it happens again

**Closed by jorenn92** 2024-02-10 00:36 UTC
Labels: enhancement, plex
